In [20]:
import numpy as np

In [33]:
ord1, ord2, tot = [], [], []
w1 = 'ABCDE'
w2 = 'abcde'
w3 = 'vwxyz'

In [34]:
for l in range(5):
    ord1_l, ord2_l = [], []
    for j_1 in range(5):
        ord1_l.append(w1[j_1])                    # A, B, C, D, E
        for j_2 in range(j_1+1, 5):
            # print(j_1, " ", j_2)
            ord2_l.append(w2[j_2] + w1[j_1])      # a, b, c, d, e
        # print("\n")
    ord1.append(w3[l] + w2[j_2] + w1[j_1])                            # v, w, x, y, z
    ord2.append(ord2_l)
#tot = ord1.append(ord2)
#print("Ordine 1:\n", ord1, "Ordine 2:\n",ord2)

In [35]:
print(np.shape(ord1))
ord1

(5,)


['veE', 'weE', 'xeE', 'yeE', 'zeE']

In [36]:
np.shape(ord2)

(5, 10)

In [37]:
ord2

[['bA', 'cA', 'dA', 'eA', 'cB', 'dB', 'eB', 'dC', 'eC', 'eD'],
 ['bA', 'cA', 'dA', 'eA', 'cB', 'dB', 'eB', 'dC', 'eC', 'eD'],
 ['bA', 'cA', 'dA', 'eA', 'cB', 'dB', 'eB', 'dC', 'eC', 'eD'],
 ['bA', 'cA', 'dA', 'eA', 'cB', 'dB', 'eB', 'dC', 'eC', 'eD'],
 ['bA', 'cA', 'dA', 'eA', 'cB', 'dB', 'eB', 'dC', 'eC', 'eD']]

### Second method

In [39]:
a = np.arange(75)
v = a.reshape(15,5)
v

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74]])

In [40]:
f, s = [], []

In [41]:
for i in range (5):
    for j in range(5):
            f.append(v[j,i])
    s.append(v[5:,i])

In [42]:
f

[0,
 5,
 10,
 15,
 20,
 1,
 6,
 11,
 16,
 21,
 2,
 7,
 12,
 17,
 22,
 3,
 8,
 13,
 18,
 23,
 4,
 9,
 14,
 19,
 24]

In [43]:
s

[array([25, 30, 35, 40, 45, 50, 55, 60, 65, 70]),
 array([26, 31, 36, 41, 46, 51, 56, 61, 66, 71]),
 array([27, 32, 37, 42, 47, 52, 57, 62, 67, 72]),
 array([28, 33, 38, 43, 48, 53, 58, 63, 68, 73]),
 array([29, 34, 39, 44, 49, 54, 59, 64, 69, 74])]

In [44]:
# (0, 0, 1) (0, 0, 2) (0, 0, 3) (0, 0, 4) (0, 1, 2) (0, 1, 3) (0, 1, 4) (0, 2, 3) (0, 2, 4) (0, 3, 4)

Nell'array che contiene i coeff. del secondo ordine, la "l" indicizza sul primo elemento, "j_1" assume i valori:
- 0: 4 volte
- 1: 3 volte
- 2: 2 volte
- 3: 1 volta

Nel mentre "j_2" assume i valori t.c.: j_1\<j_2\<=J

- (0, 4)
- (4, 7)
- (7, 9)
- 9

- 0: 5 volte
- 1: 4 volte
- 2: 3 volte
- 3: 2 volte
- 4: 1 volta

- 0: 6 volte
- 1: 5 volte
- 2: 4 volte
- 3: 3 volte
- 4: 2 volte
- 5: 1 volta